### PR TITLE
Extend index comments

### PR DESCRIPTION
**Pull request by slomo**
Extend the indexing of objects to also include comments. Will be used to display how many comments have been given for a specific element.

### CODE REVIEW

**Comment by slomo** [comment]
@nidico could you please review 8346eec and @smouzakitis could you please review the other commits, I rearrange the code quite a bit.

**Comment by nidico** [comment]
8346eec LGTM.

**Comment by cbotsikas** [comment]
@slomo, i'll check this out and come back with comments

**Comment by cbotsikas** [comment]
This PR is part of https://github.com/policycompass/policycompass/issues/84 resolution.

**Pull request merged**
