### PR TITLE
Reformat and Cleanup Code

### PR DESCRIPTION
**Pull request by FabiApfelkern**
https://github.com/policycompass/policycompass/issues/379

### CODE REVIEW

**Comment by FabiApfelkern** [comment]
@cbotsikas @nidico  Can you have a look? I cleaned everything up and deleted unneeded code. It is not PEP8 conform. That is just to much work. And I have especially a problem with the PEP8 limit of 79 characters per line. This leads to very strange line breaks. Any opinions on this?

**Comment by FabiApfelkern** [comment]
On the other hand the line breaks are making it very good readable here on GitHub.

**Comment by nidico** [comment]
I like the 79 characters-per-line limit, but I wouldn't insist.

You can ignore certain warnings as the following:

    bin/pep8 --ignore E501,E122 apps

So we need to define the set of rules which we want to adhere (or practically - the set of rules which we ignore). In adhocracy3, we use `flake8` (pep8 + pyflakes + mccabe) with `--ignore=N805,D101,D102`.

Once this is achievied, in order to keep up with the good style, we might want to add `pep8` (or `flake8`) to our tool chain and add a pre-commit hook for this repo (however pre-commit hooks need to be installed locally manually though, which could be done through the main Makefile, but AFAIK not everybody uses this...). Any opinions?

**Comment by FabiApfelkern** [comment]
I am for a pre-commit hook. I will check it again with some checks ignored to find the best solution for us.

**Comment by FabiApfelkern** [comment]
This is not without errors for the following command: 
```
flake8 apps policycompass_services --ignore E501,F403 --exclude migrations
```
E501 - Allowing longer lines than 79 characters
F403 - Allowing imports like this: from models import *

We are excluding the migration files because they are generated by Django and should be touched.

**Comment by FabiApfelkern** [comment]
It is unused. It was an error because there was another function with the same name, but I didn't want to delete it.

**Comment by nidico** [comment]
> This is now without errors for the following command:
> 
>     flake8 apps policycompass_services --ignore E501,F403 --exclude migrations

Really? I get a lots of issues such as `D101`, `D102`, `Q000` with `flake8` (not with `pep8` though).

**Comment by FabiApfelkern** [comment]
D, Q? Where does this come from? Flake has just the following: https://flake8.readthedocs.org/en/latest/warnings.html

**Comment by cbotsikas** [comment]
@FabiApfelkern i think @nidico has flake8 extensions installed. Specifically Dxxx codes come from [pep257](http://pep257.readthedocs.org/en/latest/error_codes.html) which is tested via [flake8-docstrings](https://pypi.python.org/pypi/flake8-docstrings/0.1.0) and Q000 from [flake8-quotes](https://github.com/zheller/flake8-quotes)

**Comment by nidico** [comment]
Oh yes, indeed, I didn't think of that. Normal flake8 passes just fine, neat.

**Comment by nidico** [comment]
Let's merge now and do the post-commit hook separately.

**Pull request merged**
