### PR TITLE
add post_delete signal to metric

### PR DESCRIPTION
**Pull request by MagdaN**
goes together with this one: https://github.com/policycompass/policycompass-frontend/pull/460

@FabiApfelkern: I don't know if this is the best solution for it. Do you have better ideas?

### CODE REVIEW

**Comment by cbotsikas** [comment]
You should add it on (signals.py)[https://github.com/policycompass/policycompass-services/blob/master/apps/metricsmanager/signals.py], not on this file.

**Comment by cbotsikas** [comment]
also, the clean_datasets method would be more appropriate within the dataset module, and hook it up in your metric's signal

**Comment by MagdaN** [comment]
where should I put it? datasetmanager/internal_api.py?

**Comment by cbotsikas** [comment]
sounds like a good place. You can name it probably "delete_by_metric" or something

**Pull request merged**
