### PR TITLE
Metricsmanager rewrite

### PR DESCRIPTION
**Pull request by slomo**
* remove old code (now known as datset manager)
* add models for metrics (as container of formula)
* implement rest endpoints
* validate formula while uploading

### CODE REVIEW

**Comment by FabiApfelkern** [comment]
Two issues with this PR:
- You changed a model but didn't create a migration for it. This leads to the following error when trying to migrate: 
"Your models have changes that are not yet reflected in a migration, and so won't be applied."
- Usually we only push into forks and we are not working with branches in the base repo

**Comment by slomo** [comment]
I would leave that PR here, since it has been opened here.

**Comment by FabiApfelkern** [comment]
Please be aware that executing this new initial migration might cause a problem in deployment because a user input is required.

**Comment by nidico** [comment]
Shouldn't be a problem, because we're deploying interactively anyway.

**Comment by slomo** [comment]
@FabiApfelkern do you know how to prevent this?

**Comment by FabiApfelkern** [comment]
No idea. But like @nidico said, it s ok this one time to make it manually.

**Pull request merged**
