### PR TITLE
Deploy automatically with travis

### PR DESCRIPTION
**Pull request by slomo**

### CODE REVIEW

**Comment by slomo** [comment]
@cbotsikas Please look at this one. Once it  is merge it should trigger a build on the stage server.

**Comment by cbotsikas** [comment]
Is this going to deploy _after_ the PR is merged?

**Comment by cbotsikas** [comment]
I think you time-traveled :stuck_out_tongue_winking_eye: 
LGTM, i'll merge when Travis finishes. Can you add the same on frontent? (ATM, nothing will be checked, just return true or something, we'll figure out some test in the future)

**Comment by slomo** [comment]
Lets see first if that PR flies and than add it to frontend.

**Comment by slomo** [comment]
This is the relevant build: https://travis-ci.org/policycompass/policycompass-services/builds/144481641

**Comment by slomo** [comment]
Well that didn't went so well.

**Comment by cbotsikas** [comment]
I think we are also missing instructions to run only on master, otherwise when you create a branch and PR it, it runs twice:
```
branches:
  only:
    - "master"
```
This has nothing to do with the fact that the deployment didn't work.

**Comment by slomo** [comment]
Well that only works if you use the official deployment framework, which we dont. Don't worry I have lot of similar and even more complicated setups on travis :smile:

**Pull request merged**
