### PR TITLE
add custom scale

### PR DESCRIPTION
**Pull request by mmilaprat**
PR related wit issue policycompass/policycompass/issues/538

This PR adds 2 new fiels into the visualisation model.

### CODE REVIEW

**Comment by mmilaprat** [comment]
@FabiApfelkern can you merge this PR, it is related with a the PR policycompass/policycompass-frontend/pull/429 that is merged.

**Comment by FabiApfelkern** [comment]
Done. Please check it on Stage.

**Comment by mmilaprat** [comment]
have you executed the migration ?

**Comment by FabiApfelkern** [comment]
yes

**Comment by mmilaprat** [comment]
the migration must be created two new fields in the table "datasets in visualization" (unit & scale). I checked tthe table with the Django and the fields doesn't exist.

**Comment by FabiApfelkern** [comment]
ok. it was applied but I needed to restart the server. I didn't know this.

**Comment by mmilaprat** [comment]
now it works. Thanks

**Pull request merged**
