### PR TITLE
Fix automatic travis deployment

### PR DESCRIPTION
**Pull request by slomo**

### CODE REVIEW

**Comment by slomo** [comment]
The relevant build is https://travis-ci.org/policycompass/policycompass-services/builds/144493404

**Comment by cbotsikas** [comment]
i think it worked :)

**Comment by slomo** [comment]
Yeah it worked.

**Comment by cbotsikas** [comment]
cool, can you prepare the travis for frontend too? it would be node environment without script or if needed just return true or something...

**Comment by slomo** [comment]
Apperently we have even a test setup with karma, let me just check out whether it works.

**Comment by cbotsikas** [comment]
Yes we have karma and protractor test but none of them work or pass.
We need the Travis hooks and configuration for deployment without any tests at the moment.
We can figure the tests afterwords, if we have time but for the time being, we don't use them..

**Pull request merged**
