### PR TITLE
Remove acronym from metrics and datasets

### PR DESCRIPTION
**Pull request by slomo**

### CODE REVIEW

**Comment by slomo** [comment]
@FabiApfelkern Can you please review this?

**Comment by MagdaN** [comment]
LGTM migration worked

**Comment by cbotsikas** [comment]
what about indicators?

**Comment by FabiApfelkern** [comment]
And visualisation... Each developer is responsible for their modules.

**Comment by cbotsikas** [comment]
visualisations don't have acronyms. that's why i thought it would be a single fix for all three modules. anyway.

**Comment by mmilaprat** [comment]
visualisation don't have acronyms

**Comment by cbotsikas** [comment]
part of https://github.com/policycompass/policycompass/issues/486 and https://github.com/policycompass/policycompass/issues/464

**Pull request merged**
