### PR TITLE
Rename some fields in visualisation model to add auth

### PR DESCRIPTION
**Pull request by mmilaprat**
Rename user_id as creator_path

### CODE REVIEW

**Comment by mmilaprat** [comment]
Can I merge this PR?

**Comment by FabiApfelkern** [comment]
Is it really side-effect free? Are you sure the user_id is not uses anywhere at the moment, so things might break?

**Comment by mmilaprat** [comment]
We don't use it. This filed will be used to add auth into the FE and BE

**Comment by FabiApfelkern** [comment]
Yes we don't use it, but it might be referenced somewhere anywhere, e.g. in the frontend. have you checked that?

**Comment by mmilaprat** [comment]
in the visualisation controler there are 2 references to the user_id, but they are just to fullfil the json that it will be send to the API to create or update a visualisation. It don't cause any problem.

**Pull request merged**
