### PR TITLE
Refactor visualizationsmanager

### PR DESCRIPTION
**Pull request by slomo**

### CODE REVIEW

**Comment by slomo** [comment]
@mmilaprat Is that okay for you? I basically dropped all dead code removed log messages left over from debugging and ran dos2unix (fixes /n/r to /n as line ending).

Since this is rather huge it will probably conflict with all other changes to the metrics manager that might be ongoing.

**Comment by mmilaprat** [comment]
@slomo, at this moment I don't have any update of the visualisation manager.

**Comment by cbotsikas** [comment]
Looks good to me. Didn't test it but reviewed each commit.

**Comment by mmilaprat** [comment]
who is going to accept this PR?

**Comment by cbotsikas** [comment]
@mmilaprat I've merged it

**Comment by mmilaprat** [comment]
thanks

**Pull request merged**
